### ISSUE TITLE
ImportError: No module named docopt

### ISSUE THREAD

**Issue by cryptax** [hellman/xortool#10]
Hi, 
You should add in the install pre-requisite that docopt is necessary to use xortool.
Otherwise you get:
<code>
Traceback (most recent call last):
  File "/usr/local/bin/xortool", line 39, in <module>
    from xortool.args import parse_parameters, ArgError
  File "/usr/local/lib/python2.7/dist-packages/xortool/args.py", line 4, in <module>
    from docopt import docopt
ImportError: No module named docopt
</code>
Simply installing docopt solves the issue:
<code>
pip install docopt
</code>

**Comment by hellman** [comment]
Right, I forgot to mention it in README. If you install xortool with pip, docopt is installed automatically

**Comment by rebroad** [comment]
What is going on with this? This still appears to be an issue.

**Comment by hellman** [comment]
sudo apt-get install python-pip

**Comment by miparnisari** [comment]
Also, for newbies like me, you could mention that you need to run `sudo python setup.py install` :)

**Comment by brandonros** [comment]
```
$ uname -a
Darwin Brandons-MacBook-Pro-2.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
```

```
$ sudo python setup.py install
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
running build_scripts
running install_lib
running install_scripts
changing mode of /usr/local/bin/xortool-xor to 755
changing mode of /usr/local/bin/xortool to 755
running install_egg_info
Removing /Library/Python/2.7/site-packages/xortool-0.98-py2.7.egg-info
Writing /Library/Python/2.7/site-packages/xortool-0.98-py2.7.egg-info
```

```
$ xortool
Traceback (most recent call last):
  File "/usr/local/bin/xortool", line 52, in <module>
    from xortool.args import parse_parameters, ArgError
  File "/Library/Python/2.7/site-packages/xortool/args.py", line 4, in <module>
    from docopt import docopt
ImportError: No module named docopt
```

Mac OS Mojave
