### ISSUE TITLE
Installation issue on Windows

### ISSUE THREAD

**Issue by codecowboy** [hellman/xortool#11]
I tried installing this on windows with `easy_install xortool` which succeeded but the xortool command is not recognised. If I try to run it from c:\Python27\Scripts, Windows tries to open the file in a text editor.

Python is version 2.7. Running on Windows 10 in a Virtualbox VM using Powershell.

**Comment by disconnect3d** [comment]
Just install it using `pip`:
```
λ py -m pip install xortool
You are using pip version 7.0.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting xortool
  Downloading xortool-0.95.tar.gz
Installing collected packages: xortool
  Running setup.py install for xortool
Successfully installed xortool-0.95
```

Where `py` is my `python`.

Of course you have to install `pip` first, if you don't have it already installed.
