### ISSUE TITLE
Issue importing COLORS line 55 xortool file

### ISSUE THREAD

**Issue by mccloven27** [hellman/xortool#30]
I get an error importing the name COLORS from xortool.colors, it appears that COLORS is not defined in the file

Traceback (most recent call last):
  File "xortool", line 55, in <module>
    from xortool.colors import (
ImportError: cannot import name 'COLORS' from 'xortool.colors' (C:\Users\jmccl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\xortool\colors.py)

**Comment by mccloven27** [comment]
For anyone that wants to run this, I wasn't able to get it working as it stood but by simply removing all the color tags in the main file I managed to make it run. Everything was in black and white but as far as I could tell it worked.

**Comment by hellman** [comment]
This is strange, please reopen if the issue persists.
