### ISSUE TITLE
xortool : command not found

### ISSUE THREAD

**Issue by RollandSteven** [hellman/xortool#31]
I already type this on the terminal
python3 -m pip install xortool
then i want to use it, but it says xortool: command not found
Would you help me? Thx
(I'm using python 3.8 and linux)

**Comment by hellman** [comment]
If you run it as user, it gets installed to something like /home/user/.local/bin/xortool , can you check there? may be you don't have PATH set correctly.

**Comment by RollandSteven** [comment]
I already in .local/bin and type dir in terminal, it shows xortool xortool-xor but when i type cd xortool/ it says bash: cd: xortool/: not a directory, is it installed?

**Comment by RollandSteven** [comment]
I just installed python 2.7 and it works now, thank you very much for your attention.
