### ISSUE TITLE
Can your tool analyse binary files that are xor-scrambled?

### ISSUE THREAD

**Issue by KOLANICH** [hellman/xortool#36]
Assumptions:

* constant key
* but: the scrambled data is not aligned to scrambling key. I mean that xor block size can be for example integer count of bytes, but plaintext symbol may occupy 6 bits, 7 bits, 13 bits, etc.
* the underlying data is integers, so there may be lot of zero-bits in the plaintext.
* endianness is known

**Comment by hellman** [comment]
It does not support bit-level key length, but if your data is long enough then the key repeated 8 times will be byte-aligned and should be recoverable.
