### ISSUE TITLE
Incorrect comparison 

### ISSUE THREAD

**Issue by kukuruku20** [hellman/xortool#43]
[Here](https://github.com/hellman/xortool/blob/0410f90d6f3a61a38d390aa030d01b90f01684e9/xortool/tool_main.py#L299)  `chars_count[char]` expected to be greater or equal to `max_count`, when `max_count`  contains maximum of all values in `chars_count` meaning it cannot be greater than `max_count` . What is an expected behavior here?

**Comment by hellman** [comment]
Indeed, should be just == . Not incorrect but misleading maybe.
This block catches all chars at a given offset that have the maximum frequency (we can not distinguish them).
